project_id = "fwummhpxwwelpoqtjpiw"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.news-sitemap]
    verify_jwt = false
  [functions.send-news-digest]
    verify_jwt = false
